Timestamp can be null when getting from map
Kept getting this error on `Geolocator().placemarkFromCoordinates(lat, lon)`:

```E/flutter ( 5311): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter ( 5311): NoSuchMethodError: The method 'toInt' was called on null.
E/flutter ( 5311): Receiver: null
E/flutter ( 5311): Tried calling: toInt()```

Changed the constant and moved the logic to constant declaration itself. Have tested the change, it works.